# Generated by Django 5.1.3 on 2024-11-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products')),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('specification', models.TextField()),
            ],
        ),
    ]
