# Generated by Django 5.1.3 on 2024-12-30 14:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0004_remove_cart_image_remove_cart_name_remove_cart_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 12, 30, 19, 35, 49, 114630))),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('On the Way', 'On the way')], default='pending', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='ekart.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
