# Generated by Django 5.1.3 on 2025-03-20 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0006_contact_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 20, 4, 6, 241665)),
        ),
    ]
